=== bashnesnos/grepp/src/main/resources/config/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.smltools.org/config"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://www.smltools.org/config">

	<complexType name="root">
		<sequence>
			<element ref="tns:defaults" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:postProcessSeparators" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:logDateFormats" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:config" maxOccurs="unbounded" minOccurs="0"></element>
			<element ref="tns:processThreads" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:postProcessColumns" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:filterAliases" maxOccurs="1" minOccurs="0"></element>
		</sequence>
	</complexType>


	<complexType name="defaults">
		<sequence>
			<element ref="tns:spoolFileExtension" maxOccurs="1" minOccurs="0"></element>
            <element ref="tns:resultsDir" maxOccurs="1" minOccurs="0"></element>
            <element ref="tns:postProcessSeparator" maxOccurs="1" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="postProcessSeparators">
		<sequence>
			<element ref="tns:separator" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>


	<complexType name="separator">
		<sequence>
			<element ref="tns:spoolFileExtension" maxOccurs="1" minOccurs="1"></element>
			<element ref="tns:value" maxOccurs="1" minOccurs="1"></element>
		</sequence>
		<attribute name="id" type="string"></attribute>				
	</complexType>

	<complexType name="logDateFormats">
		<sequence>
			<element ref="tns:dateFormat" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="dateFormat">
		<sequence>
			<element ref="tns:value" maxOccurs="1" minOccurs="1"></element>
			<element ref="tns:regex" maxOccurs="1" minOccurs="1"></element>
		</sequence>
		<attribute name="id" type="string"></attribute>				
	</complexType>

	<complexType name="pattern" mixed="true">
		<simpleContent>
			<extension base="string">
				<attribute name="tags" type="string"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<element name="spoolFileExtension" type="string"></element>

	<element name="postProcessSeparator" type="string"></element>

	<element name="value" type="string"></element>

	<element name="regex" type="string"></element>

	<element name="separator" type="tns:separator"></element>

    <element name="resultsDir" type="string"></element>

	<element name="pattern" type="tns:pattern"></element>

	<complexType name="config">
		<sequence>
			<element ref="tns:logDateFormat" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:starter" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:logThreshold" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:pattern" maxOccurs="1" minOccurs="0"></element>
		</sequence>
		<attribute name="id" type="string"></attribute>
	</complexType>

	<element name="logDateFormat" type="string"></element>

	<element name="starter" type="string"></element>

	<element name="date" type="string"></element>

	<element name="logThreshold" type="string"></element>

	<element name="config" type="tns:config"></element>

	<complexType name="processThreads">
		<sequence>
			<element ref="tns:extractors" maxOccurs="1" minOccurs="1"></element>
			<element ref="tns:skipends" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:ends" maxOccurs="1" minOccurs="1"></element>
		</sequence>
	</complexType>



	<complexType name="thread_patterns">
		<sequence>
			<element ref="tns:pattern" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<element name="extractors" type="tns:thread_patterns"></element>

	<element name="skipends" type="tns:thread_patterns"></element>

	<element name="ends" type="tns:thread_patterns"></element>

	<element name="processThreads" type="tns:processThreads"></element>

	<complexType name="postProcessColumns">
		<sequence>
			<element ref="tns:splitter" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="splitter">
		<simpleContent>
			<extension base="tns:pattern">
				<attribute name="col_name" type="string"></attribute>
				<attribute name="type" type="string"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<element name="splitter" type="tns:splitter"></element>

	<element name="postProcessColumns" type="tns:postProcessColumns"></element>

	<complexType name="filterAliases">
		<sequence>
			<element ref="tns:filter" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>


	<element name="filter" type="tns:pattern"></element>

	<element name="filterAliases" type="tns:filterAliases"></element>

	<element name="defaults" type="tns:defaults"></element>

	<element name="postProcessSeparators" type="tns:postProcessSeparators"></element>

	<element name="root" type="tns:root"></element>

<<<<<<< Updated upstream
    <element name="results_dir" type="string"></element>

    <element name="params_factory" type="string"></element>
=======
>>>>>>> Stashed changes
</schema>

=== bashnesnos/grepp/src/main/resources/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="http://www.smltools.org/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.smltools.org/config config.xsd">
	<defaults>
		<spoolFileExtension>.log</spoolFileExtension>
		<resultsDir>results</resultsDir>
		<postProcessSeparator>csv</postProcessSeparator>
	</defaults>
	<postProcessSeparators>
		<separator id="csv">
			<spoolFileExtension>.csv</spoolFileExtension>
			<value>,</value>
		</separator>
		<separator id="piped">
			<spoolFileExtension>.txt</spoolFileExtension>
			<value>|</value>
		</separator>
	</postProcessSeparators>
	<logDateFormats>
		<dateFormat id="iso">
			<value>yyyy-MM-dd HH:mm:ss</value>
			<regex>(\d{4}-\d{1,2}-\d{1,2} \d{2}:\d{2}:\d{2})</regex>
		</dateFormat>
	</logDateFormats>
    <config id="properties">
		<starter>log4j.logger</starter>
		<pattern>.*\.properties</pattern>
	</config>
	<config id="to_test">
		<logDateFormat>iso</logDateFormat>
		<starter>####\[\D{1,}\].*</starter>
		<logThreshold>4</logThreshold>
		<pattern>fpTest_</pattern>
	</config>
    <config id="pr_test">
		<logDateFormat>iso</logDateFormat>
		<logThreshold>24</logThreshold>
		<pattern>processing_</pattern>
	</config>
    <processThreads>
			<extractors>
				<pattern tags="to_test,pr_test">ThreadStart: '\d{1,}'</pattern>	
			</extractors>
			<skipends>
				<pattern tags="to_test,pr_test">SkipPattern</pattern>
			</skipends>
			<ends>
				<pattern tags="to_test,pr_test">ThreadEnd1</pattern>
				<pattern tags="to_test,pr_test">ThreadEnd2</pattern>
			</ends>
		</processThreads>
    <postProcessColumns>
		<splitter col_name="some_cmd" tags="count_ops" type="filter">Command name="?(.*?)"</splitter>
		<splitter col_name="count_of_operands" tags="count_ops" type="counter">(operand)</splitter>
		<splitter col_name="some_cmd" tags="group_ops" type="group">Command name="?(.*?)"</splitter>
		<splitter col_name="count_of_operands" tags="group_ops" type="counter">(operand)</splitter>
		<splitter col_name="some_cmd" tags="group_op_values" type="group">Command name="?(.*?)"</splitter>
		<splitter col_name="operands" tags="group_op_values" type="rfilter">operand='(.*?)'</splitter>
		<splitter col_name="some_cmd" tags="avg_timings" type="group">Command name="?(.*?)"</splitter>
		<splitter col_name="avg_processing" tags="avg_timings" type="avg">time="?(\d*)"</splitter>
		<splitter col_name="some_cmd" tags="avg_operands" type="group">Command name="?(.*?)"</splitter>
		<splitter col_name="avg_operands" tags="avg_operands" type="avg">(operand)</splitter>
	</postProcessColumns>
    <filterAliases>
			<filter tags="predef">Something::</filter>
			<filter tags="foo">Foo</filter>
			<filter tags="group_op_values,group_ops,count_ops,avg_timings">oo</filter>
	</filterAliases>
</root>
